sources:
  - name: nytaxi
    database: project-481a6090-10e3-4ce0-9bf
    schema: m4_nytaxi
    
    tables:
      - name: green_tripdata
        identifier: green_tripdata  # ← Add explicit identifier
      - name: yellow_tripdata
        identifier: yellow_tripdata  # ← Add explicit identifier